import type { CatalogProductDto } from '@/types/commerce';

// ─── Shared mock entities ─────────────────────────────────────────────────────

const BRANDS = {
  maison:   { id: 'brand-1', name: 'Maison Shoozy', slug: 'maison-shoozy' },
  atelier:  { id: 'brand-2', name: 'Atelier M',     slug: 'atelier-m'     },
  nordico:  { id: 'brand-3', name: 'Nordico',        slug: 'nordico'       },
  classico: { id: 'brand-4', name: 'Classico Roma',  slug: 'classico-roma' },
};

const CATEGORIES = {
  sneakers: { id: 'cat-1', name: 'Sneakers',    slug: 'sneakers',    isPrimary: true },
  loafers:  { id: 'cat-2', name: 'Loafers',     slug: 'loafers',     isPrimary: true },
  boots:    { id: 'cat-3', name: 'Boots',        slug: 'boots',       isPrimary: true },
  sandals:  { id: 'cat-4', name: 'Sandals',      slug: 'sandals',     isPrimary: true },
  oxfords:  { id: 'cat-5', name: 'Oxfords',      slug: 'oxfords',     isPrimary: true },
  derby:    { id: 'cat-6', name: 'Derby Shoes',  slug: 'derby-shoes', isPrimary: true },
  slippers: { id: 'cat-7', name: 'Slippers',     slug: 'slippers',    isPrimary: true },
};

// Stable Unsplash images
const IMAGES = {
  sneaker1:  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
  sneaker2:  'https://images.unsplash.com/photo-1491553154775-e2b6e0c72d4b?auto=format&fit=crop&w=800&q=80',
  sneaker3:  'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80',
  sneaker4:  'https://images.unsplash.com/photo-1512374382973-ab72e4a7e2b0?auto=format&fit=crop&w=800&q=80',
  loafer1:   'https://images.unsplash.com/photo-1614252235316-8ce61f4f4fd3?auto=format&fit=crop&w=800&q=80',
  loafer2:   'https://images.unsplash.com/photo-1595950653106-bde1d103a5c8?auto=format&fit=crop&w=800&q=80',
  loafer3:   'https://images.unsplash.com/photo-1468436139062-f60851436d66?auto=format&fit=crop&w=800&q=80',
  boot1:     'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80',
  boot2:     'https://images.unsplash.com/photo-1605733160314-4fc07c393a61?auto=format&fit=crop&w=800&q=80',
  sandal1:   'https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=800&q=80',
  sandal2:   'https://images.unsplash.com/photo-1562273138-21ae49e49ad7?auto=format&fit=crop&w=800&q=80',
  oxford1:   'https://images.unsplash.com/photo-1484178853349-f80e4e1a1b0f?auto=format&fit=crop&w=800&q=80',
  oxford2:   'https://images.unsplash.com/photo-1463100099107-aa0980c362a6?auto=format&fit=crop&w=800&q=80',
  slipper1:  'https://images.unsplash.com/photo-1582562124811-8898a563ec36?auto=format&fit=crop&w=800&q=80',
  slipper2:  'https://images.unsplash.com/photo-1591985695763-aa8929e8e0f4?auto=format&fit=crop&w=800&q=80',
};

// ─── Mock Product Array ───────────────────────────────────────────────────────

export const mockProducts: CatalogProductDto[] = [

  // ── Sneakers ──────────────────────────────────────────────────────────────
  {
    id: 'prod-001',
    name: 'Air Luxe Runner',
    slug: 'air-luxe-runner',
    shortDescription: 'Lightweight mesh upper with cloud-foam sole.',
    basePrice: '320000',
    compareAtPrice: null,
    minimumVariantPriceMinor: '320000',
    minimumEffectivePriceMinor: '320000',
    inStock: true,
    gender: 'MALE',
    season: 'SUMMER',
    publishedAt: '2026-01-10T10:00:00Z',
    brand: BRANDS.maison,
    categories: [CATEGORIES.sneakers],
    primaryMedia: { id: 'media-001', type: 'IMAGE', altText: 'Air Luxe Runner', url: IMAGES.sneaker1 },
    secondaryMedia: { id: 'media-001b', type: 'IMAGE', altText: 'Air Luxe Runner side', url: IMAGES.sneaker2 },
  },
  {
    id: 'prod-002',
    name: 'Urban Street Low — Chalk White Edition',
    slug: 'urban-street-low-chalk-white',
    shortDescription: 'Street-ready profile meets premium calfskin.',
    basePrice: '480000',
    compareAtPrice: '560000',
    minimumVariantPriceMinor: '480000',
    minimumEffectivePriceMinor: '430000',
    promotionalPricing: {
      originalPriceMinor: '480000',
      effectivePriceMinor: '430000',
      discountMinor: '50000',
      discountPercentageBasisPoints: '1041',
      promotions: [{ discountId: 'disc-1', name: 'Summer Sale', type: 'PERCENTAGE', value: '10', amountMinor: '50000', endsAt: '2026-08-31T23:59:59Z' }],
    },
    inStock: true,
    gender: 'MALE',
    season: 'ALL_SEASON',
    publishedAt: '2026-02-15T10:00:00Z',
    brand: BRANDS.atelier,
    categories: [CATEGORIES.sneakers],
    primaryMedia: { id: 'media-002', type: 'IMAGE', altText: 'Urban Street Low', url: IMAGES.sneaker2 },
    secondaryMedia: null,
  },
  {
    id: 'prod-003',
    name: 'Velocity Knit Pro',
    slug: 'velocity-knit-pro',
    shortDescription: null,
    basePrice: '290000',
    compareAtPrice: null,
    minimumVariantPriceMinor: '290000',
    minimumEffectivePriceMinor: '290000',
    inStock: false, // OUT OF STOCK
    gender: 'FEMALE',
    season: 'SPRING',
    publishedAt: '2026-03-01T10:00:00Z',
    brand: BRANDS.nordico,
    categories: [CATEGORIES.sneakers],
    primaryMedia: { id: 'media-003', type: 'IMAGE', altText: 'Velocity Knit Pro', url: IMAGES.sneaker3 },
    secondaryMedia: null,
  },
  {
    id: 'prod-004',
    name: 'Retro Suede High — Limited Drop No.7 Autumn Collection',
    slug: 'retro-suede-high-limited-drop-7',
    shortDescription: 'Italian suede with hand-stitched ankle collar.',
    basePrice: '650000',
    compareAtPrice: '780000',
    minimumVariantPriceMinor: '650000',
    minimumEffectivePriceMinor: '585000',
    promotionalPricing: {
      originalPriceMinor: '650000',
      effectivePriceMinor: '585000',
      discountMinor: '65000',
      discountPercentageBasisPoints: '1000',
      promotions: [{ discountId: 'disc-2', name: 'VIP Member', type: 'PERCENTAGE', value: '10', amountMinor: '65000', endsAt: null }],
    },
    inStock: true,
    gender: 'UNISEX',
    season: 'AUTUMN',
    publishedAt: '2026-04-05T10:00:00Z',
    brand: BRANDS.maison,
    categories: [CATEGORIES.sneakers],
    primaryMedia: { id: 'media-004', type: 'IMAGE', altText: 'Retro Suede High', url: IMAGES.sneaker4 },
    secondaryMedia: { id: 'media-004b', type: 'IMAGE', altText: 'Retro Suede High side', url: IMAGES.sneaker1 },
  },

  // ── Loafers ───────────────────────────────────────────────────────────────
  {
    id: 'prod-005',
    name: 'Milano Penny Loafer',
    slug: 'milano-penny-loafer',
    shortDescription: 'Burnished calf leather with leather-lined insole.',
    basePrice: '520000',
    compareAtPrice: null,
    minimumVariantPriceMinor: '520000',
    minimumEffectivePriceMinor: '520000',
    inStock: true,
    gender: 'MALE',
    season: 'ALL_SEASON',
    publishedAt: '2026-01-20T10:00:00Z',
    brand: BRANDS.classico,
    categories: [CATEGORIES.loafers],
    primaryMedia: { id: 'media-005', type: 'IMAGE', altText: 'Milano Penny Loafer', url: IMAGES.loafer1 },
    secondaryMedia: null,
  },
  {
    id: 'prod-006',
    name: 'Tassel Velvet Loafer',
    slug: 'tassel-velvet-loafer',
    shortDescription: 'Midnight blue velvet with gold tassel detail.',
    basePrice: '595000',
    compareAtPrice: '680000',
    minimumVariantPriceMinor: '595000',
    minimumEffectivePriceMinor: '540000',
    inStock: false, // OUT OF STOCK
    gender: 'MALE',
    season: 'WINTER',
    publishedAt: '2026-05-12T10:00:00Z',
    brand: BRANDS.maison,
    categories: [CATEGORIES.loafers],
    primaryMedia: { id: 'media-006', type: 'IMAGE', altText: 'Tassel Velvet Loafer', url: IMAGES.loafer2 },
    secondaryMedia: null,
  },
  {
    id: 'prod-007',
    name: 'Horsebit Leather Loafer',
    slug: 'horsebit-leather-loafer',
    shortDescription: 'Polished calfskin with antique brass hardware.',
    basePrice: '720000',
    compareAtPrice: null,
    minimumVariantPriceMinor: '720000',
    minimumEffectivePriceMinor: '720000',
    inStock: true,
    gender: 'FEMALE',
    season: 'ALL_SEASON',
    publishedAt: '2026-06-01T10:00:00Z',
    brand: BRANDS.atelier,
    categories: [CATEGORIES.loafers],
    primaryMedia: { id: 'media-007', type: 'IMAGE', altText: 'Horsebit Loafer', url: IMAGES.loafer3 },
    previewVideo: null,
    secondaryMedia: { id: 'media-007b', type: 'IMAGE', altText: 'Horsebit Loafer angled', url: IMAGES.loafer1 },
  },
  {
    id: 'prod-008',
    name: 'Monk Strap Mule',
    slug: 'monk-strap-mule',
    shortDescription: 'A backless silhouette with monkstrap closure.',
    basePrice: '440000',
    compareAtPrice: null,
    minimumVariantPriceMinor: '440000',
    minimumEffectivePriceMinor: '440000',
    inStock: true,
    gender: 'UNISEX',
    season: 'SPRING',
    publishedAt: '2026-07-08T10:00:00Z',
    brand: BRANDS.nordico,
    categories: [CATEGORIES.loafers],
    primaryMedia: null, // Tests the image-fallback UI
    secondaryMedia: null,
  },

  // ── Boots ─────────────────────────────────────────────────────────────────
  {
    id: 'prod-009',
    name: 'Chelsea Boot — Dark Cognac',
    slug: 'chelsea-boot-dark-cognac',
    shortDescription: 'Elastic side panel, leather outsole, hand-stitched welt.',
    basePrice: '780000',
    compareAtPrice: '900000',
    minimumVariantPriceMinor: '780000',
    minimumEffectivePriceMinor: '710000',
    inStock: true,
    gender: 'MALE',
    season: 'AUTUMN',
    publishedAt: '2026-02-28T10:00:00Z',
    brand: BRANDS.classico,
    categories: [CATEGORIES.boots],
    primaryMedia: { id: 'media-009', type: 'IMAGE', altText: 'Chelsea Boot Cognac', url: IMAGES.boot1 },
    secondaryMedia: null,
  },
  {
    id: 'prod-010',
    name: 'Combat Leather Lace-Up',
    slug: 'combat-leather-lace-up',
    shortDescription: 'Chunky platform sole, lace-up closure.',
    basePrice: '860000',
    compareAtPrice: null,
    minimumVariantPriceMinor: '860000',
    minimumEffectivePriceMinor: '860000',
    inStock: false, // OUT OF STOCK
    gender: 'FEMALE',
    season: 'WINTER',
    publishedAt: '2026-03-15T10:00:00Z',
    brand: BRANDS.maison,
    categories: [CATEGORIES.boots],
    primaryMedia: { id: 'media-010', type: 'IMAGE', altText: 'Combat Lace-Up', url: IMAGES.boot2 },
    secondaryMedia: null,
  },

  // ── Sandals ───────────────────────────────────────────────────────────────
  {
    id: 'prod-011',
    name: 'Capri Strappy Sandal',
    slug: 'capri-strappy-sandal',
    shortDescription: 'Hand-woven leather straps on a cork bed.',
    basePrice: '310000',
    compareAtPrice: null,
    minimumVariantPriceMinor: '310000',
    minimumEffectivePriceMinor: '310000',
    inStock: true,
    gender: 'FEMALE',
    season: 'SUMMER',
    publishedAt: '2026-04-20T10:00:00Z',
    brand: BRANDS.atelier,
    categories: [CATEGORIES.sandals],
    primaryMedia: { id: 'media-011', type: 'IMAGE', altText: 'Capri Strappy Sandal', url: IMAGES.sandal1 },
    secondaryMedia: null,
  },
  {
    id: 'prod-012',
    name: 'Contoured Footbed Sandal — Midnight Black Nubuck Limited Release',
    slug: 'contoured-footbed-midnight-black',
    shortDescription: 'Anatomical cork footbed with adjustable straps.',
    basePrice: '270000',
    compareAtPrice: '340000',
    minimumVariantPriceMinor: '270000',
    minimumEffectivePriceMinor: '250000',
    inStock: true,
    gender: 'UNISEX',
    season: 'SUMMER',
    publishedAt: '2026-05-05T10:00:00Z',
    brand: BRANDS.nordico,
    categories: [CATEGORIES.sandals],
    primaryMedia: { id: 'media-012', type: 'IMAGE', altText: 'Contoured Footbed Sandal', url: IMAGES.sandal2 },
    secondaryMedia: { id: 'media-012b', type: 'IMAGE', altText: 'Contoured Footbed alt', url: IMAGES.sandal1 },
  },

  // ── Oxfords ───────────────────────────────────────────────────────────────
  {
    id: 'prod-013',
    name: 'Cap-Toe Oxford — Midnight Black',
    slug: 'cap-toe-oxford-midnight-black',
    shortDescription: 'Goodyear-welted, full-grain leather upper.',
    basePrice: '920000',
    compareAtPrice: null,
    minimumVariantPriceMinor: '920000',
    minimumEffectivePriceMinor: '920000',
    inStock: true,
    gender: 'MALE',
    season: 'ALL_SEASON',
    publishedAt: '2026-01-05T10:00:00Z',
    brand: BRANDS.classico,
    categories: [CATEGORIES.oxfords],
    primaryMedia: { id: 'media-013', type: 'IMAGE', altText: 'Cap-Toe Oxford Black', url: IMAGES.oxford1 },
    secondaryMedia: null,
  },
  {
    id: 'prod-014',
    name: 'Wingtip Brogue Oxford',
    slug: 'wingtip-brogue-oxford',
    shortDescription: 'Traditional brogue perforations on a derby last.',
    basePrice: '840000',
    compareAtPrice: '980000',
    minimumVariantPriceMinor: '840000',
    minimumEffectivePriceMinor: '780000',
    inStock: true,
    gender: 'MALE',
    season: 'AUTUMN',
    publishedAt: '2026-02-10T10:00:00Z',
    brand: BRANDS.maison,
    categories: [CATEGORIES.oxfords, { ...CATEGORIES.derby, isPrimary: false }],
    primaryMedia: { id: 'media-014', type: 'IMAGE', altText: 'Wingtip Brogue Oxford', url: IMAGES.oxford2 },
    secondaryMedia: { id: 'media-014b', type: 'IMAGE', altText: 'Wingtip Brogue side', url: IMAGES.oxford1 },
  },

  // ── Slippers ──────────────────────────────────────────────────────────────
  {
    id: 'prod-015',
    name: 'Cashmere-Lined Indoor Moccasin',
    slug: 'cashmere-lined-indoor-moccasin',
    shortDescription: 'Shearling insole, supple suede exterior.',
    basePrice: '250000',
    compareAtPrice: null,
    minimumVariantPriceMinor: '250000',
    minimumEffectivePriceMinor: '250000',
    inStock: true,
    gender: 'UNISEX',
    season: 'WINTER',
    publishedAt: '2026-06-20T10:00:00Z',
    brand: BRANDS.nordico,
    categories: [CATEGORIES.slippers],
    primaryMedia: { id: 'media-015', type: 'IMAGE', altText: 'Cashmere Moccasin', url: IMAGES.slipper1 },
    secondaryMedia: null,
  },
  {
    id: 'prod-016',
    name: 'Velvet Smoking Slipper',
    slug: 'velvet-smoking-slipper',
    shortDescription: 'Embroidered velvet upper, leather outsole.',
    basePrice: '390000',
    compareAtPrice: '450000',
    minimumVariantPriceMinor: '390000',
    minimumEffectivePriceMinor: '350000',
    inStock: false, // OUT OF STOCK
    gender: 'MALE',
    season: 'ALL_SEASON',
    publishedAt: '2026-07-01T10:00:00Z',
    brand: BRANDS.maison,
    categories: [CATEGORIES.slippers],
    primaryMedia: { id: 'media-016', type: 'IMAGE', altText: 'Velvet Smoking Slipper', url: IMAGES.slipper2 },
    secondaryMedia: null,
  },
];

